### ISSUE TITLE
Information text for Attorney

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#381]
Please provide the following informational text for the “Attorney Information” as a dropdown. 

“The only attorneys who may sign responses and otherwise practice before the USPTO in trademark matters are as follows:

(1)	Attorneys in good standing with a bar of the highest court of any U.S. state, the District of Columbia, Puerto Rico, and other U.S. commonwealths or U.S. territories; and 

(2)	Canadian agents/attorneys who represent owners of the mark located in Canada and (a) are registered with the USPTO and in good standing as patent agents or (b) have been granted reciprocal recognition by the USPTO.”

![image](https://user-images.githubusercontent.com/44168600/53184057-63783900-35ca-11e9-99a2-6101e5d30acf.png)

**Comment by dutchTender** [comment]
i ll get this next. will put screen shot when it has been completed.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53356713-077b2080-38fa-11e9-93b9-31b6edaccae3.png)

**Comment by nguyenvivi** [comment]
This issue has not been resolved.

Please provide the following **_collapsible informational text_** for the “Attorney Information”:

“The only attorneys who may sign responses and otherwise practice before the USPTO in trademark matters are as follows:

(1)	Attorneys in good standing with a bar of the highest court of any U.S. state, the District of Columbia, Puerto Rico, and other U.S. commonwealths or U.S. territories; and 

(2)	Canadian agents/attorneys who represent owners of the mark located in Canada and (a) are registered with the USPTO and in good standing as patent agents or (b) have been granted reciprocal recognition by the USPTO.”

**Comment by l-stanny** [comment]
@JackieBabos @dutchTender @serra-trinh This has been completed locally and will be in the next GitHub push
![Screen Shot 2019-03-14 at 5 06 33 PM](https://user-images.githubusercontent.com/8275852/54391615-c0bc5300-467b-11e9-9b35-c0a5173f6add.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56459911-a2c3cb80-6368-11e9-98c6-ff35e50bd07a.png)
