### ISSUE TITLE
date validation for foreign registration date and first in use date, and first in commerce date

### ISSUE THREAD

**Issue by dutchTender** [GrantThorntonETSI/eFile_Reimagined#461]
1. foreign registration (prevents any future dates)
goods and services level and class level

2. first commerce date and first in use date must be within 6 month of each other (this may be revised later)

**Comment by JackieBabos** [comment]
If the date of first use of the Mark in commerce pre-dates the date of first use of the Mark anywhere, the system shall generate an error message. 

 "The date of first use in commerce cannot be earlier than the date of first use anywhere."

**Comment by JackieBabos** [comment]
The issue the user had when testing this section was the user received the 44d error when she clicked "no" to the "Do you have a registration and/or pending application in a foreign country for same goods/services?". So that error should have never popped up since this error only corresponds to the foreign application filing date.
